import React, { useState, useEffect } from 'react';
import api from '../../utils/api';
import { CheckCircle, Clock, Calendar, TrendingUp, Award, Target } from 'lucide-react';

const WorkerOverview = () => {
  const [tasks, setTasks] = useState({ pending: [], completed: [] });
  const [stats, setStats] = useState({
    todayTasks: 2,
    completed: 5,
    pending: 1,
    weeklyScore: 94
  });
  const [aiSummary, setAiSummary] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchTasks();
    generateAISummary();
  }, []);

  const fetchTasks = async () => {
    try {
      const response = await api.get('/tasks/my-tasks');
      setTasks(response.data);
    } catch (error) {
      console.error('Failed to fetch tasks:', error);
      // Mock data
      setTasks({
        pending: [
          { _id: '1', taskType: 'Farmer Awareness Campaign', description: 'Conduct awareness campaign in Kurnool region', dueDate: new Date().setHours(17, 0, 0, 0) }
        ],
        completed: [
          { _id: '2', taskType: 'Survey Collection', description: 'Collect beneficiary data', completedAt: new Date() }
        ]
      });
    }
  };

  const generateAISummary = async () => {
    try {
      const response = await api.post('/ai/summary');
      setAiSummary(response.data.summary);
    } catch (error) {
      console.error('Failed to generate summary:', error);
      setAiSummary('Conducted farmer training in Kurnool with 35 attendees. Primary concern raised was irrigation water shortage across 3 villages. Women participated in the survey, with a total of 62% recommending a follow-up survey next week.');
    } finally {
      setLoading(false);
    }
  };

  const statCards = [
    { label: "Today's tasks", value: stats.todayTasks, icon: Calendar, color: 'bg-blue-500' },
    { label: "Completed", value: stats.completed, icon: CheckCircle, color: 'bg-green-500' },
    { label: "Pending", value: stats.pending, icon: Clock, color: 'bg-yellow-500' },
    { label: "Weekly score", value: `${stats.weeklyScore}%`, icon: TrendingUp, color: 'bg-purple-500' },
  ];

  return (
    <div className="space-y-6">
      {/* Stats Grid */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {statCards.map((stat, index) => {
          const Icon = stat.icon;
          return (
            <div key={index} className="bg-white rounded-xl shadow-sm p-4">
              <div className="flex items-center justify-between mb-2">
                <div className={`${stat.color} p-2 rounded-lg`}>
                  <Icon className="w-4 h-4 text-white" />
                </div>
                <span className="text-2xl font-bold text-gray-900">{stat.value}</span>
              </div>
              <p className="text-sm text-gray-600">{stat.label}</p>
            </div>
          );
        })}
      </div>

      {/* Assigned Today */}
      <div className="bg-white rounded-xl shadow-sm p-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center space-x-2">
            <Target className="w-5 h-5 text-purple-600" />
            <h3 className="text-lg font-semibold text-gray-900">ASSIGNED TODAY</h3>
          </div>
          <span className="text-sm text-gray-500">Due 5 PM today</span>
        </div>
        
        {tasks.pending.length > 0 ? (
          tasks.pending.map(task => (
            <div key={task._id} className="border-l-4 border-purple-600 pl-4 py-2">
              <h4 className="font-semibold text-gray-900">{task.taskType}</h4>
              <p className="text-sm text-gray-600 mt-1">Region: Kurnool · Due {new Date(task.dueDate).toLocaleTimeString()}</p>
              <button className="mt-2 px-4 py-1 bg-purple-600 text-white rounded-lg text-sm hover:bg-purple-700 transition-all">
                Log activity ▼
              </button>
            </div>
          ))
        ) : (
          <p className="text-gray-500">No tasks assigned for today</p>
        )}
      </div>

      {/* AI Summary */}
      <div className="bg-gradient-to-r from-purple-50 to-indigo-50 rounded-xl p-6">
        <div className="flex items-center space-x-2 mb-3">
          <Award className="w-5 h-5 text-purple-600" />
          <h3 className="font-semibold text-gray-900">AI SUMMARY · YESTERDAY</h3>
        </div>
        <p className="text-gray-700 leading-relaxed">
          {loading ? 'Generating AI summary...' : aiSummary}
        </p>
        <p className="text-xs text-gray-500 mt-2">Generated by FieldSync AI</p>
      </div>
    </div>
  );
};

export default WorkerOverview;